# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VqfJQxpxxAI7HCtq7_Yq4oT70H68TTn0
"""

n = int(input('Введите порядковый номер: '))
if n == 1:
  print("Январь")
if n == 2:
  print("Февраль")
if n == 3:
  print("Март")
if n == 5:
  print("Май")
if n == 6:
  print("Июнь")
if n == 7:
  print("Июль")
if n == 8:
  print("Август")
if n == 9:
  print("Сентябрь")
if n == 10:
  print("Октябрь")
if n == 11:
  print("Ноябрь")
if n == 12:
  print("Декабрь")